### ISSUE TITLE
Effects: Meta

### ISSUE THREAD

**Issue by IrateRedKite** [TheStarport/ChaosMod#3]
- [x] **Double time**: Doubles the timer bar
- [x] **Double effect time**: Doubles the active effect time
- [x] **Box of Chocolates**: Hide the Effect UI
- [x] **Fake crash**: Loops audio and minimizes the game
